on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  yarn-build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4

      - run: yarn install
      - run: yarn build

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
